
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 23;
  public static final int RIGHT_PAREN = 39;
  public static final int PERIOD = 37;
  public static final int DOUBLE_CONST = 45;
  public static final int DOUBLE = 11;
  public static final int SEMI = 35;
  public static final int INTERFACE = 3;
  public static final int INT = 10;
  public static final int PRINTLN = 15;
  public static final int LESS = 25;
  public static final int FOR = 18;
  public static final int MINUS = 21;
  public static final int NOT = 33;
  public static final int AND = 31;
  public static final int OR = 32;
  public static final int LEFT_BRACE = 42;
  public static final int COMMA = 36;
  public static final int BOOL = 13;
  public static final int CLASS = 2;
  public static final int NEWARRAY = 14;
  public static final int PLUS = 20;
  public static final int ASSIGN = 34;
  public static final int IF = 6;
  public static final int RIGHT_BRKT = 41;
  public static final int ID = 48;
  public static final int EOF = 0;
  public static final int RETURN = 8;
  public static final int GTR = 27;
  public static final int INT_CONST = 44;
  public static final int error = 1;
  public static final int LEFT_BRKT = 40;
  public static final int RIGHT_BRACE = 43;
  public static final int MOD = 24;
  public static final int BREAK = 9;
  public static final int VOID = 17;
  public static final int READLN = 16;
  public static final int EQ = 29;
  public static final int ELSE = 7;
  public static final int NOT_EQ = 30;
  public static final int WHILE = 19;
  public static final int LESS_EQ = 26;
  public static final int EXTENDS = 5;
  public static final int LEFT_PAREN = 38;
  public static final int MULTI = 22;
  public static final int BOOL_CONST = 47;
  public static final int STRING = 12;
  public static final int STRING_CONST = 46;
  public static final int GTR_EQ = 28;
  public static final int IMPLEMENTS = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASS",
  "INTERFACE",
  "IMPLEMENTS",
  "EXTENDS",
  "IF",
  "ELSE",
  "RETURN",
  "BREAK",
  "INT",
  "DOUBLE",
  "STRING",
  "BOOL",
  "NEWARRAY",
  "PRINTLN",
  "READLN",
  "VOID",
  "FOR",
  "WHILE",
  "PLUS",
  "MINUS",
  "MULTI",
  "DIVIDE",
  "MOD",
  "LESS",
  "LESS_EQ",
  "GTR",
  "GTR_EQ",
  "EQ",
  "NOT_EQ",
  "AND",
  "OR",
  "NOT",
  "ASSIGN",
  "SEMI",
  "COMMA",
  "PERIOD",
  "LEFT_PAREN",
  "RIGHT_PAREN",
  "LEFT_BRKT",
  "RIGHT_BRKT",
  "LEFT_BRACE",
  "RIGHT_BRACE",
  "INT_CONST",
  "DOUBLE_CONST",
  "STRING_CONST",
  "BOOL_CONST",
  "ID"
  };
}

